---
title: "Relevance-Recall"
author: "Pinar Larsson"
date: "14 Dec 2015"
output: word_document
---

Here comes the frequency table that i have used to determine the correlation between Relevance and Recall.
Both data are ordinal and symbolizes different answers for each type.

Relevance type: 0 stands for answer options 1-2, 1 stands for the answer option 3 and 2 stands for options 4-5.

Recall type: 0 stands for no and 1 stands for yes.

Note that as the order increases, we obtain more positive answers for both types.

Here comes the frequeny table for our data:

df_temp <- data.frame("1"=c(712,449,236), "2"=c(507,704,710))
colnames(df_temp)[1] = 0
colnames(df_temp)[2] = 1
rownames(df_temp)[1] = 0
rownames(df_temp)[2] = 1
rownames(df_temp)[3] = 2

which looks like this: 
    0   1
0 712 507
1 449 704
2 236 710

Applying Goodman and Kruskal's gamma (since both are ordinal), we get the following gamma and p-value (with confidence level 0.95):

library(MESS)
gkgamma(df_temp, conf.level = 0.95)

Goodman-Kruskal's gamma for ordinal categorical data

data:  structure(c(712, 449, 236, 507, 704, 710), .Dim = c(3L, 2L), .Dimnames = list(    c("0", "1", "2"), c("0", "1")))
Z = 109.81, p-value < 2.2e-16
95 percent confidence interval:
 0.4360714 0.4471481
sample estimates:
Goodman-Kruskal's gamma 
              0.4416097 
              
There is a moderately strong positive correlation between recall and relevance (not so strong or so weak) and since p-value < 0.05 we can conclude that the association between Recall and Relevance is statistically significant.